#!/bin/bash
echo
echo
echo "###########################################"
echo "              mencoder"
echo "###########################################"
grabImageByMplayer $1 10 2

echo
echo
echo "###########################################"
echo "              FFmpeg"
echo "###########################################"
grabImageByFFmpeg $1

echo
echo
echo "###########################################"
echo "              show media size"
echo "###########################################"
du -a *.jpg
