#!/usr/local/bin/php
<?php
	$min = $argv[1];
	$max = $argv[2];
	if (count($argv) <= 3) {
		$step = 1;
	} else {
		$step = $argv[3];
	} 
	$nums = range($min, $max, $step);
	echo implode("\n", $nums);

?>
