#!/bin/bash
pid=$1

if [[ "$pid" = "" ]]; then
	echo "No pid input !"
	exit
fi

echo "
AggressiveOpts
CompileThreshold
LargePageSizeInBytes
MaxHeapFreeRatio
MaxNewSize
MaxPermSize
MinHeapFreeRatio
NewRatio
NewSize
ReservedCodeCacheSize
SurvivorRatio
TargetSurvivorRatio
ThreadStackSize
UseBiasedLocking
UseFastAccessorMethods
UseLargePages
UseStringCache
AllowUserSignalHandlers
DisableExplicitGC
FailOverToOldVerifier
MaxFDLimit
PreBlockSpin
RelaxAccessControlCheck
ScavengeBeforeFullGC
UseAltSigs
UseBoundThreads
UseConcMarkSweepGC
UseGCOverheadLimit
UseLWPSynchronization
UseParallelGC
UseParallelOldGC
UseSerialGC
UseSpinning
UseTLAB
UseSplitVerifier
UseThreadPriorities
UseVMInterruptibleIO
UseG1GC
MaxGCPauseMillis
InitiatingHeapOccupancyPercent
NewRatio
SurvivorRatio
MaxTenuringThreshold
ParallelGCThreads
ConcGCThreads
G1ReservePercent
G1HeapRegionSize
AllocatePrefetchLines
AllocatePrefetchStyle
UseCompressedStrings
OptimizeStringConcat
CITime
ErrorFile
ExtendedDTraceProbes
HeapDumpPath
HeapDumpOnOutOfMemoryError
OnError
" | xargs -I {} jinfo -flag {} $pid


